SELECT CONCAT('/home/grep/src/',A.BOARD_ID,'/',A.FILE_ID,A.FILE_NAME,A.FILE_EXT)
FROM USED_GOODS_FILE A
LEFT JOIN USED_GOODS_BOARD B
ON A.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY A.FILE_ID DESC;